projectName: cdciWithHardis
devHubAlias: DevHub_cdciWithHardis
developmentBranch: integration
autoCleanTypes:
  - destructivechanges
  - flowPositions
  - minimizeProfiles
devHubUsername: cristiaan3003@gmail.com.hardis.devhub
poolConfig:
  maxScratchOrgsNumber: 5
  storageService: salesforce
deploymentPlan:
  packages: []
